apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-migrations
  labels:
    {{- include "url-platform.labels" . | nindent 4 }}
data:
  V1__create_analytics_table.sql: |
    {{ .Files.Get "migrations/analytics/V1__create_analytics_table.sql" | nindent 4 }}
