{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-platform
  labels:
    {{- include "url-platform.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.paths.redirectPrefix | quote }}
            pathType: Prefix
            backend:
              service:
                name: redirect-service
                port:
                  number: {{ .Values.redirectService.port }}
          - path: {{ .Values.ingress.paths.statsPrefix | quote }}
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: {{ .Values.analyticsService.port }}
          - path: {{ .Values.ingress.paths.rootPrefix | quote }}
            pathType: Prefix
            backend:
              service:
                name: url-service
                port:
                  number: {{ .Values.urlService.port }}
{{- end }}
