kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: url-platform
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 30000
        protocol: TCP
      - containerPort: 443
        hostPort: 30001
        protocol: TCP
