apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: url-platform
type: Opaque
stringData:
  POSTGRES_USER: CHANGE_ME_USER
  POSTGRES_PASSWORD: CHANGE_ME_PASSWORD
  DATABASE_URL: postgresql://CHANGE_ME_USER:CHANGE_ME_PASSWORD@postgres:5432/url_platform
