apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-platform
  namespace: url-platform
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /r
            pathType: Prefix
            backend:
              service:
                name: redirect-service
                port:
                  number: 8080
          - path: /stats
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: url-service
                port:
                  number: 3000
